### ISSUE TITLE
settings.py.erb out of date with master

### ISSUE THREAD

**Issue by robzienert** [bflad/chef-skyline#2]
It appears that the settings template is out of date with master; having missing configuration points:

```
> [#] Mixlib::ShellOut::ShellCommandFailed
> [#]        ------------------------------------
> [#]        Expected process to exit with [0], but received '1'
> [#]        ---- Begin output of /etc/init.d/skyline-analyzer start ----
> [#]        STDOUT: Starting skyline-analyzer
> [#]        failed to start analyzer-agent
> [#]        STDERR: Traceback (most recent call last):
> [#]          File "/opt/skyline/bin/../src/analyzer/analyzer-agent.py", line 13, in <module>
> [#]            from analyzer import Analyzer
> [#]          File "/opt/skyline/src/analyzer/analyzer.py", line 17, in <module>
> [#]            from algorithms import run_selected_algorithm
> [#]          File "/opt/skyline/src/analyzer/algorithms.py", line 11, in <module>
> [#]            from settings import (
> [#]        ImportError: cannot import name ENABLE_SECOND_ORDER
> [#]        ---- End output of /etc/init.d/skyline-analyzer start ----
> [#]        Ran /etc/init.d/skyline-analyzer start returned 1
```

**Comment by yportnoy** [comment]
@robzienert did you ever get past this issue?
